version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception

  # wordpress:
  #   build: ./requirements/wordpress
  #   container_name: wordpress
  #   env_file: .env
  #   depends_on:
  #     - mariadb
  #   volumes:
  #     - wordpress_data:/var/www/html
  #   networks:
  #     - inception

  # nginx:
  #   build: ./requirements/nginx
  #   container_name: nginx
  #   depends_on:
  #      - wordpress
  #   ports:
  #     - "443:443"
  #   volumes:
  #     - ./requirements/nginx:/var/www/html
  #   networks:
  #     - inception

volumes:
  mariadb_data:
  wordpress_data:

networks:
  inception:
    driver: bridge