version: '3.8'

services:
  mariadb:
    build: ./requirements/mariadb
    container_name: mariadb
    env_file: .env
    volumes:
      - /home/mavi/data/mariadb_data:/var/lib/mysql
      # - mariadb_data:/var/lib/mysql
    networks:
      - inception
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart : always

  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress
    env_file: .env
    depends_on:
      - mariadb
    volumes:
      - /home/mavi/data/wordpress_data:/var/www/html
      # - wordpress_data:/var/www/html
    networks:
      - inception
    restart : always

  nginx:
    build: ./requirements/nginx
    container_name: nginx
    depends_on:
      - wordpress
    ports:
      - "443:443"
    volumes:
      - /home/mavi/data/wordpress_data:/var/www/html
      # - wordpress_data:/var/www/html
    networks:
      - inception
    restart : always

# volumes:
#   mariadb_data:
#   wordpress_data:

#fonti da guardare -> https://docs.docker.com/engine/storage/volumes/

networks:
  inception:
    driver: bridge